import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'

// This file is auto-generated by `eslint.config.js`.
export default tseslint.config(
  { ignores: ['dist'] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    // This is the recommended configuration for TypeScript.
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    // This rule is recommended by the React Refresh plugin.
    // It ensures that components are only exported once, which is important
    // for the hot reloading feature to work correctly.
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
    },
  },
)
