server:
  port: 6111

spring:
  cloud:
    gateway:
      routes:
        - id: payment-service-create
          uri: lb://payment-service
          predicates:
            - Path=/createOrder
          filters:
            - AuthenticationFilter

        - id: payment-service-verify
          uri: lb://payment-service
          predicates:
            - Path=/verify
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: train-service
          uri: lb://train-service
          predicates:
            - Path=/trains/**
          filters:
            - AuthenticationFilter

        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/tickets/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6010/eureka
