spring.application.name=user-service
server.port=PORT_NUMBER
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_name
spring.datasource.username=root
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=Your_SECTRET_KEY

# Eureka Server Configuration
eureka.client.service-url.defaultZone=http://localhost:PORT_NUMBER/eureka