spring:
  application:
    name: eureka-server
server:
  port: 6010

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:6010/eureka/
  server:
    enable-self-preservation: false  # Disable in development
    eviction-interval-timer-in-ms: 5000
    renewal-percent-threshold: 0.49
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: INFO  # Changed from OFF to see registration logs
    com.netflix.discovery: INFO
    org.springframework.web: DEBUG