name: Deploy Railway System to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'Microservices/**'
      - 'eureka-server/**'
      - 'api-gateway/**'

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service:
          - name: eureka-server
            path: eureka-server
            port: 6010
          - name: api-gateway
            path: api-gateway
            port: 6111
          - name: user-service
            path: Microservices/user-service
            port: 5000
          - name: train-service
            path: Microservices/train-service
            port: 5010
          - name: ticket-service
            path: Microservices/ticket-service
            port: 5020
          - name: payment-service
            path: Microservices/payment-service
            port: 5030

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build ${{ matrix.service.name }}
        run: |
          cd ${{ matrix.service.path }}
          mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.path }}
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ matrix.service.name }}:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ matrix.service.name }} \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ matrix.service.name }}:latest \
            --registry-login-server ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label railway-${{ matrix.service.name }}-$(date +%s) \
            --ports ${{ matrix.service.port }} \
            --cpu 1 \
            --memory 1.5 \
            --environment-variables SPRING_PROFILES_ACTIVE=azure